"""Smoke test for scales._biobabel.

Generated by `biobabel new contract`. Edit to actually exercise the package's
public API (this template only verifies importability).
"""

from __future__ import annotations


def main() -> None:
    import scales  # noqa: F401
    print("imported scales successfully")


if __name__ == "__main__":
    main()
